import style from "./privacy.module.css"

const PrivacyPage = () => {
    return (
        <div className={style.main}>
            <div className={style.mainHolder}>
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h1>Privacy Policy</h1>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Update date: May 31, 2024</p>

                        <p>Effective Date: May 31, 2024</p>

                        <p>Glanceme.Ai website, Rotenx apps for all platforms, rotenx devtool extensions are products of Glanceme.Ai Inc., which is registered and located in Gwalior, MP, INDIA.</p>

                        <p>At Glanceme.Ai, we are committed to protecting your privacy. This privacy policy describes our policies and procedures on the collection, use and disclosure of your information when you use the service and tells you about your privacy rights and how the law protects you.</p>

                        <p> We use your personal data to provide and improve the service. By using the service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    </div>
                </div>


                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2>Interpretation and Definitions</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Interpretation</p>
                        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                        <p> Definitions</p>
                        <p>For the purposes of this Privacy Policy:</p>
                        <p><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</p>
                        <p><b>Application</b> means the software program provided by the Company downloaded by You on any electronic device, named rotenx devtool Chrome & Edge extension, and rotenx APP for other OS.</p>
                        <p><b>Company</b> {"("}referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement{")"} refers to Rotenx Inc.</p>
                        <p><b>Device</b> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
                        <p><b>Personal</b> Data is any information that relates to an identified or identifiable individual.</p>
                        <p><b>Service</b> refers to the Application</p>
                        <p><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                        <p><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself {"("}for example, the duration of a page visit{")"}.</p>
                        <p><b>You</b> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                    </div>
                </div>



                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2>Collecting and Using Your Personal Data</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Types of Data Collected</p>
                        <p>Personal Data</p>
                        <p>While using Our Service, Rotenx DevTool may ask you to provide certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to: your email, your name, your phone number if you choose to login with your phone number, etc.</p>
                        <p>Usage Data</p>
                        <p>Collected automatically when using the Service.</p>
                        <p>Usage Data may include information such as your browser type, operating system, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other diagnostic data.</p>
                        <p>Additionally, when you use certain functions of our Service, such as reading a page, analyzing documents, and other features, we may also collect the URLs involved in these activities to better understand how you interact with our Service and to improve functionality.</p>
                        <p>Use of Your Personal Data</p>
                        <p>The Company may use Personal Data for the following purposes:</p>



                        <p>To provide and maintain our Service, including to monitor the usage of our Service.</p>
                        <p><b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
                        <p><b>For the performance of a contract:</b> the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.</p>
                        <p><b>To contact You:</b> To contact You by email or other equivalent forms of electronic communication, such as a mobile application{"'"}s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation.</p>
                        <p><b>To manage Your requests:</b> To attend and manage Your requests to Us.</p>
                        <p><b>For other purposes:</b> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.</p>

                        <p>We may share Your personal information in the following situations:</p>

                        <p><b>With Service Providers:</b> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</p>
                        <p><b>With other users:</b> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</p>
                        <p><b>With Your consent:</b> We may disclose Your personal information for any other purpose with Your consent.</p>
                        <p><b>Third-Party Services</b> You can choose to permit or restrict Third-Party Services. Third-Party Services may integrate with our services, and you can enable or disable the integrations. Once enabled, the Third-Party Service may share some information with us to facilitate the integration. You should check the privacy settings and notices in these Third-Party Services to understand the data collection, sharing, and use.</p>

                        <p>Retention of Your Personal Data</p>
                        <p>Rotenx DevTool will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations {"("}for example, if we are required to retain your data to comply with applicable laws{")"}, resolve disputes, and enforce our legal agreements and policies.</p>
                        <p>Rotenx DevTool will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

                        <p>Transfer of Your Personal Data</p>
                        <p>Your information, including Personal Data, is processed at Rotenx DevTool{"'"}s operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>

                        <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

                        <p>Rotenx DevTool will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

                        <p>Delete Your Personal Data</p>

                        <p>You have the right to delete or request that Rotenx DevTool assist in deleting the Personal Data that We have collected about You.</p>

                        <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>

                        <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>

                        <p> Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>


                        <p>Disclosure of Your Personal Data</p>
                        <p>In addition to the aforementioned policy, the following information pertains to data collection, handling, storage, and sharing by the Chrome/Edge extension and Rotenx devTool web service.</p>

                        <p>Data Collection </p>

                        <p>If you choose to save your chats on Rotenx DevTool via the Rotenx extension, your chats will be saved on Rotenx DevTool servers in the Amazon US data center.</p>
                        <p>Your registration data will also be saved on Rotenx DevTool servers in the Amazon US data center.</p>
                        <p>Your browser version may be saved and used to diagnose problems you experience.</p>
                        <p>If you choose to upload and save files, such as HTML and PDF files on the Rotenx DevTool website, those data will be saved on Rotenx DevTool servers in the Amazon US data center.</p>
                        <p>We may use tools like Google Analytics to collect usage data.</p>


                        <p><b>Data Handling</b></p>

                        <p>Data is transferred to servers through HTTPS.</p>
                        <p>The company has strict restrictions on your data. Basically, no one will be able to access your data unless you request us to diagnose data-related issues for you.</p>
                        <p>We may get statistical information about your data, such as how many new chats the service has today, etc.</p>
                        <p>We may use third-party services like Google Analytics to collect some usage data.</p>
                        <p>We will not sell your data to any third party.</p>
                        <p>You can choose to delete your account and remove all data stored on our servers.</p>

                        <p><b>Data Storage</b></p>

                        <p>The data is stored in Amazon servers based in the US.</p>
                        <p>We use a backup system in Amazon to back up the data.</p>
                        <p>We utilize security services, such as firewalls, to safeguard your data.</p>

                        <p><b>Data Sharing</b></p>

                        <p>We may use some third-party services, such as Google Analytics, to collect some usage data, so some usage data is shared with those services.</p>
                        <p>You can choose to share your chats with AI with other users.</p>
                        <p>If you choose to chat with AIs through our tools or services, you agree to share those data with AIs and the organization behind those AIs.</p>
                        <p>Your chat data is not shared with any other third parties, except when required by law enforcement.</p>
                        <p>Disclosure of Your Personal Data</p>

                        <p>Rotenx DevTool may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

                        <p>Comply with a legal obligation.</p>
                        <p>Protect and defend the rights or property of Rotenx DevTool.</p>
                        <p>Prevent or investigate possible wrongdoing in connection with the Service.</p>
                        <p>Protect the personal safety of users of the Service or the public.</p>
                        <p>Protect against legal liability.</p>


                        <p>Business Transactions</p>

                        <p>If Rotenx DevTool is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

                        <p>Law Enforcement</p>

                        <p>Under certain circumstances, Rotenx DevTool may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities {"("}e.g., a court or a government agency{")"}.</p>

                        <p>Other Legal Requirements</p>

                        <p>Rotenx DevTool may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

                        <p>Comply with a legal obligation.</p>
                        <p>Protect and defend the rights or property of Rotenx DevTool.</p>
                        <p>Prevent or investigate possible wrongdoing in connection with the Service.</p>
                        <p>Protect the personal safety of Users of the Service or the public.</p>
                        <p>Protect against legal liability.</p>
                        <p>GDPR Compliance</p>

                        <p>We updated our Privacy Policy to comply with the requirements of the General Data Protection Regulation {"("}GDPR{")"}, which is the European Union data protection law that went into effect on May 25, 2018.</p>

                        <p>Security of Your Personal Data</p>

                        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                    </div>
                </div>


                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2>Children{"'"}s Privacy</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                        <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent{"'"}s consent before We collect and use that information.</p>
                    </div>
                </div>

                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2>Links to Other Websites</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party{"'"}s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                        <p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
                    </div>
                </div>

                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2>Changes to this Privacy Policy</h2>
                    </div>
                    <div className={style.mainContainerPara}>

                        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

                        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                    </div>
                </div>

                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2>Contact Us</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                        <p>By email: anshitmishra03@gmail.com</p>
                    </div>
                </div>
            </div>
        </div >
    )
}

export default PrivacyPage;