import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Alert from "./components/utils/alert/alert";
import Providers from "./redux/provider/provider";
import Header from "./(portal)/component/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <Header></Header>
        <section>
          <Alert />
        </section>
        {children}
        </Providers>
        </body>
    </html>
  );
}
