"use client"
import Header from "../home/header/header";
import style from "./privacy.module.css"
import { useEffect, useRef } from "react";

const PrivacyPage = () => {
    return (
        <div className={style.main}>
            <div className={style.mainBg}></div>
            <Header />
            <div className={style.mainHolder}>
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h1 className={style.sectionTitleGradient}>Privacy Policy</h1>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p className={style.updateDate}>Update date: May 31, 2024</p>
                        <p className={style.effectiveDate}>Effective Date: May 31, 2024</p>

                        <p>Glanceme.Ai website, glanceme apps for all platforms, glanceme devtool extensions are products of Glanceme.Ai pvt ltd., which is registered and located in Pune, Maharashtra, INDIA.</p>

                        <p>At Glanceme.Ai, we are committed to protecting your privacy. This privacy policy describes our policies and procedures on the collection, use and disclosure of your information when you use the service and tells you about your privacy rights and how the law protects you.</p>

                        <p>We use your personal data to provide and improve the service. By using the service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    </div>
                </div>

                {/* Interpretation and Definitions */}
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2 className={style.sectionTitleGradient}>Interpretation and Definitions</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <h3 className={style.sectionSubheading}>Interpretation</h3>
                        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                        
                        <h3 className={style.sectionSubheading}>Definitions</h3>
                        <p>For the purposes of this Privacy Policy:</p>
                        
                        <div className={style.definitionList}>
                            <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
                            <p><strong>Application</strong> means the software program provided by the Company downloaded by You on any electronic device, named glanceme devtool Chrome & Edge extension, and glanceme APP for other OS.</p>
                            <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to glanceme pvt ltd.</p>
                            <p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
                            <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                            <p><strong>Service</strong> refers to the Application</p>
                            <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                            <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                            <p><strong>You</strong> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                        </div>
                    </div>
                </div>

                {/* Collecting and Using Your Personal Data */}
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2 className={style.sectionTitleGradient}>Collecting and Using Your Personal Data</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <h3 className={style.sectionSubheading}>Types of Data Collected</h3>
                        
                        <h4 className={style.subsectionHeading}>Personal Data</h4>
                        <p>While using Our Service, glanceme DevTool may ask you to provide certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to: your email, your name, your phone number if you choose to login with your phone number, etc.</p>
                        
                        <h4 className={style.subsectionHeading}>Usage Data</h4>
                        <p>Collected automatically when using the Service.</p>
                        <p>Usage Data may include information such as your browser type, operating system, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other diagnostic data.</p>
                        <p>Additionally, when you use certain functions of our Service, such as reading a page, analyzing documents, and other features, we may also collect the URLs involved in these activities to better understand how you interact with our Service and to improve functionality.</p>
                        
                        <h4 className={style.subsectionHeading}>Use of Your Personal Data</h4>
                        <p>The Company may use Personal Data for the following purposes:</p>
                        <ul className={style.purposeList}>
                            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                            <li><strong>For the performance of a contract:</strong> the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.</li>
                            <li><strong>To contact You:</strong> To contact You by email or other equivalent forms of electronic communication, such as a mobile application push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation.</li>
                            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.</li>
                        </ul>
                    </div>
                </div>

                {/* Children's Privacy */}
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2 className={style.sectionTitleGradient}>Childrens Privacy</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                        <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parents consent before We collect and use that information.</p>
                    </div>
                </div>

                {/* Links to Other Websites */}
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2 className={style.sectionTitleGradient}>Links to Other Websites</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third partys site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                        <p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
                    </div>
                </div>

                {/* Changes to this Privacy Policy */}
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2 className={style.sectionTitleGradient}>Changes to this Privacy Policy</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                    </div>
                </div>

                {/* Contact Us */}
                <div className={style.mainContainer}>
                    <div className={style.mainContainerHeading}>
                        <h2 className={style.sectionTitleGradient}>Contact Us</h2>
                    </div>
                    <div className={style.mainContainerPara}>
                        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                        <p>By email: support@glanceme.ai</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default PrivacyPage;